K9CleanSweep/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace K9CleanSweep.Models
{
    public class Review
    {
        [Key]
        public int ReviewID { get; set; }

        [Required(ErrorMessage = "Please Enter A Title")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please Enter A Review")]
        public string Message { get; set; }

        public string Author { get; set; }

        [Required]
        [Range(1, 5)]
        public int starRating { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime ReviewDate { get; set; }

        [ForeignKey("ClientID")]
        public int ClientID { get; set; }

    }
}

K9CleanSweep/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using K9CleanSweep.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace K9CleanSweep.Controllers
{
    public class ClientController : Controller
    {
        string cs = "Server=(localdb)\\MSSQLLocalDB;Database=CleanSweepDB;Trusted_Connection=True;";

        public IActionResult ClientOrder(Client client)
        {
            int _clientID = Startup.status.GetUserID();
            string queryString = "SELECT * FROM dbo.clients WHERE ClientID = " + _clientID;
            using (SqlConnection conn = new SqlConnection(cs))
            {
                SqlCommand getClient = new SqlCommand(queryString, conn);
                conn.Open();

                SqlDataReader reader = getClient.ExecuteReader();

                int clientID = reader.GetOrdinal("ClientID");
                int clientUserName = reader.GetOrdinal("ClientUserName");
                int clientPassword = reader.GetOrdinal("Password");
                int clientEmail = reader.GetOrdinal("Email");
                int clientFullName = reader.GetOrdinal("ClientName");
                int clientAddress = reader.GetOrdinal("Address");
                int clientPostalCode = reader.GetOrdinal("PostalCode");
                int clientDogs = reader.GetOrdinal("AmountOfDogs");
                int clientYard = reader.GetOrdinal("YardSqFootage");
                int clientService = reader.GetOrdinal("Service");
                int clientServiceDateTime = reader.GetOrdinal("ServiceDateTime");
                int clientNotes = reader.GetOrdinal("Notes");

                while (reader.Read())
                {
                    client.ClientID = reader.GetInt32(clientID);
                    client.ClientUserName = reader.GetString(clientUserName);
                    client.Password = reader.GetString(clientPassword);
                    client.Email = reader.GetString(clientEmail);
                    client.ClientName = reader.GetString(clientFullName);
                    client.Address = reader.GetString(clientAddress);
                    client.PostalCode = reader.GetString(clientPostalCode);
                    client.AmountOfDogs = reader.GetInt32(clientDogs);
                    client.YardSqFootage = reader.GetDecimal(clientYard);
                    client.Service = reader.GetString(clientService);
                    client.ServiceDateTime = reader.GetString(clientServiceDateTime);
                    client.Notes = reader.GetString(clientNotes);
                }
                //Sets Up Users Info On The Status Object
                Startup.status.SetUsername(client.ClientUserName);
                Startup.status.SetUserPassword(client.Password);
                Startup.status.SetUserEmail(client.Email);
                Startup.status.SetAddress(client.Address);
                Startup.status.SetPostalCode(client.PostalCode);
                Startup.status.SetFullName(client.ClientName);
                Startup.status.SetService(client.Service);
                Startup.status.SetServiceDateTime(client.ServiceDateTime);
                Startup.status.SetDogAmount(client.AmountOfDogs);
                Startup.status.SetYardSize(client.YardSqFootage);
                Startup.status.SetNotes(client.Notes);
                conn.Close();
            }
            return View(client);
        }

        [HttpGet]
        public ViewResult EditClientDetails()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EditClientDetails(Client client)
        {
            
                using (SqlConnection myConn = new SqlConnection(cs))
                {
                    SqlCommand updateClientInfo = new SqlCommand();
                    updateClientInfo.Connection = myConn;
                    myConn.Open();

                    updateClientInfo.CommandType = CommandType.StoredProcedure;
                    updateClientInfo.CommandText = "spUpdateClientInfo";

                    updateClientInfo.Parameters.AddWithValue("@clientID", client.ClientID);
                    updateClientInfo.Parameters.AddWithValue("@username", client.ClientUserName);
                    updateClientInfo.Parameters.AddWithValue("@password", client.Password);
                    updateClientInfo.Parameters.AddWithValue("@email", client.Email);
                    updateClientInfo.Parameters.AddWithValue("@fullName", client.ClientName);
                    updateClientInfo.Parameters.AddWithValue("@address", client.Address);
                    updateClientInfo.Parameters.AddWithValue("@postalCode", client.PostalCode);
                    updateClientInfo.Parameters.AddWithValue("@dogs", client.AmountOfDogs);
                    updateClientInfo.Parameters.AddWithValue("@yard", client.YardSqFootage);
                    updateClientInfo.Parameters.AddWithValue("@service", client.Service);

                    //Reset The status object (All Of Currently Logged in Clients Info)
                    Startup.status.SetUsername(client.ClientUserName);
                    Startup.status.SetUserPassword(client.Password);
                    Startup.status.SetUserEmail(client.Email);
                    Startup.status.SetAddress(client.Address);
                    Startup.status.SetPostalCode(client.PostalCode);
                    Startup.status.SetFullName(client.ClientName);
                    Startup.status.SetService(client.Service);
                    Startup.status.SetDogAmount(client.AmountOfDogs);
                    Startup.status.SetYardSize(client.YardSqFootage);
                    updateClientInfo.ExecuteNonQuery();
                    myConn.Close();
                    return View("ClientOrder", client);
                }
           
        }

        [HttpGet]
        public IActionResult LeaveReview()
        {
            return View();
        }


        [HttpPost]
        public IActionResult SubmitReview(Review review)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection myConn = new SqlConnection(cs))
                {
                    SqlCommand submitReview = new SqlCommand();
                    submitReview.Connection = myConn;
                    myConn.Open();

                    submitReview.CommandType = CommandType.StoredProcedure;
                    submitReview.CommandText = "spSubmitReview";

                    submitReview.Parameters.AddWithValue("@reviewTitle", review.Title);
                    submitReview.Parameters.AddWithValue("@reviewMessage", review.Message);
                    submitReview.Parameters.AddWithValue("@clientID", Startup.status.GetUserID());
                    submitReview.Parameters.AddWithValue("@author", Startup.status.GetUsername());
                    submitReview.Parameters.AddWithValue("@rating", review.starRating);

                    submitReview.ExecuteNonQuery();
                    myConn.Close();

                    return View("Index");
                }
            }
            else
            {
                return View("ClientOrder");
            }
        }

        public IActionResult Calendar(Client client)
        {
            //Checking To See If Client Has Time / Day Picked Already
            int _clientID = Startup.status.GetUserID();
            string queryString = "SELECT * FROM dbo.clients WHERE ClientID = " + _clientID;
            using (SqlConnection conn = new SqlConnection(cs))
            {
                SqlCommand getClient = new SqlCommand(queryString, conn);
                conn.Open();

                SqlDataReader reader = getClient.ExecuteReader();

                int clientID = reader.GetOrdinal("ClientID");
                int clientServiceDateTime = reader.GetOrdinal("ServiceDateTime");

                while (reader.Read())
                {
                    client.ClientID = reader.GetInt32(clientID);
                    client.ServiceDateTime = reader.GetString(clientServiceDateTime);
                }
                if (client.ServiceDateTime == "noDate")
                {
                    //Client Needs To Pick A Date
                    return View();
                }
                else
                {
                    //Client Has Already Picked A Date
                    return View("Index");
                }
            }
        }

        [HttpPost]
        public IActionResult SetDayTime(string timeDay)
        {
            int _clientID = Startup.status.GetUserID();
            using (SqlConnection myConn = new SqlConnection(cs))
            {
                SqlCommand updateClientInfo = new SqlCommand();
                updateClientInfo.Connection = myConn;
                myConn.Open();

                updateClientInfo.CommandType = CommandType.StoredProcedure;
                updateClientInfo.CommandText = "spAddClientDayTime";

                updateClientInfo.Parameters.AddWithValue("@clientID", _clientID);
                updateClientInfo.Parameters.AddWithValue("@dayTime", timeDay);

                updateClientInfo.ExecuteNonQuery();
                myConn.Close();
                return View("ClientOrder");
            }
        }
        [HttpPost]
        public IActionResult Login(Client client)
        {

            if (client.ClientUserName == null || client.Password == null)
            {
                return View("Index");
            }
            else
            {
                using (SqlConnection myConn = new SqlConnection(cs))
                {
                    SqlCommand login = new SqlCommand();
                    login.Connection = myConn;
                    myConn.Open();

                    login.CommandType = CommandType.StoredProcedure;

K9CleanSweep/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using K9CleanSweep.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace K9CleanSweep.Controllers
{
    public class EmployeeController : Controller
    {
        string cs = "Server=(localdb)\\MSSQLLocalDB;Database=CleanSweepDB;Trusted_Connection=True;";

        public IActionResult EmpPage()
        {
            return View();
        }

        public IActionResult EmpJobs()
        {
            Employee employee = new Employee();
            List<Client> clients = Startup.utility.GetClients();
            var tuple = new Tuple<List<Client>, Employee>(clients, employee);
            return View(tuple);
        }

        [HttpGet]
        public IActionResult EmpLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EmpLogin(Employee employee)
        {
            if (employee.EmpUserName == null || employee.EmpPassword == null)
            {
                return View("EmpLogin");
            }
            else
            {
                using (SqlConnection myConn = new SqlConnection(cs))
                {
                    SqlCommand login = new SqlCommand();
                    login.Connection = myConn;
                    myConn.Open();

                    login.CommandType = CommandType.StoredProcedure;
                    login.CommandText = "spEmpLogin";

                    login.Parameters.AddWithValue("@empUsername", employee.EmpUserName);
                    login.Parameters.AddWithValue("@empPassword", employee.EmpPassword);

                    object result = login.ExecuteScalar();
                    int resultID = Convert.ToInt16(result);
                    if (resultID == 0)
                    {
                        myConn.Close();
                        return View("EmpLogin");
                    }
                    else
                    {
                        ViewBag.EmpID = resultID;
                        Startup.empStatus.Login();
                        Startup.empStatus.SetEmpID(resultID);
                        Startup.empStatus.SetEmpUsername(employee.EmpUserName);
                        myConn.Close();
                        return View("EmpPage");
                    }
                }
            }
        }

        [HttpPost]
        public IActionResult EmpLogout()
        {
            Startup.empStatus.Logout();
            return View("Index");
        }
    }
}

K9CleanSweep/Views/Shared/Index.cshtml
<div class="col-md-8" id="mainBanner">
</div>
<div class="col-md-4">
    <div id="indexLogoBanner"></div>
    <div class="quickLinksContainer">
        <form asp-controller="Home" asp-action="Contact">
            <button type="submit" class="btn btn-primary pull-right">Message Us</button>
        </form>
        <canvas id="indexCanvas" height="200" width="200">
            Apologies, your browser doesn't support Canvas!
        </canvas>
    </div>
</div>
<div class="col-md-12">
    <table class="table" id="practiceTable">
        <tr>
            <td>Bam</td>
        </tr>
        <tr>
            <td>Bam</td>
        </tr>
        <tr>
            <td>Bam</td>
        </tr>
        <tr>
            <td>Bam</td>
        </tr>
        <tr>
            <td>Bam</td>
        </tr>
    </table>
</div>

K9CleanSweep/Views/Shared/Reviews.cshtml
@model Tuple<List<Review>, Client>
@{ Layout = null;}
@{
    ViewData["clientID"] = K9CleanSweep.Startup.status.GetUserID();
    ViewData["loggedIn"] = K9CleanSweep.Startup.status.GetStatus();
    ViewData["empLoggedIn"] = K9CleanSweep.Startup.empStatus.GetStatus();
    ViewData["clientUserName"] = K9CleanSweep.Startup.status.GetUsername();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pooch-Patrol</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" id="userNavbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" id="brandName" asp-controller="Home" asp-action="Index">Pooch-Patrol</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Services">Rates</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Reviews">Reviews</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @if (ViewData["loggedIn"].ToString() == "True")
                { }
                else
                {
                    <a id="bookButton" asp-area="" class="pull-right" asp-controller="Home" asp-action="BookService">Sign Up</a>
                }
            </div>
        </div>
    </nav>
    @if (ViewData["loggedIn"].ToString() == "True")
    {
        <div id="login" class="col-md-12">
            <label class="label-info navbar-left" id="userBadge">Welcome&nbsp;@ViewData["clientUserName"]</label>
            <div class="text-center col-md-6">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="LeaveReview">Leave FeedBack</a></li>
                    <li><a asp-area="" asp-controller="Client" asp-action="ClientOrder">Your Order</a></li>
                </ul>
            </div>
            <form class="navbar-form navbar-right" method="post" asp-action="Logout">
                <button type="submit" class="btn btn-primary">Log Out</button>
            </form>
        </div>
    }
    else
    {
        <div id="login" class="col-md-12">
            <form class="navbar-form navbar-right" asp-action="Index">
                <button type="submit" class="btn btn-primary">Log In</button>
            </form>
        </div>
    }
    <div class="container body-content">
        <div class="page-header text-center pageHeader">
            <h1>Client Reviews</h1>
        </div>
        @foreach (var review in Model.Item1)
        {
            <div class="jumbotron text-center">
                <div class="text-center">
                    @switch (@review.starRating)
                    {
                        case 1: // review had 1 star
                            {
                                <p>
                                    <span id="reviewStars">
                                        &#x2605;&nbsp;
                                    </span>
                                </p>
                                break;
                            }
                        case 2: // review had 2 stars
                            {
                                <p>
                                    <span id="reviewStars">
                                        &#x2605;&nbsp;&#x2605;&nbsp;
                                    </span>
                                </p>
                                break;
                            }
                        case 3: // review had 3 stars
                            {
                                <p>
                                    <span id="reviewStars">
                                        &#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;
                                    </span>
                                </p>
                                break;
                            }
                        case 4: // review had 4 stars
                            {
                                <p>
                                    <span id="reviewStars">
                                        &#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;
                                    </span>
                                </p>
                                break;
                            }
                        case 5: // review had 5 stars
                            {
                                <p>
                                    <span id="reviewStars">
                                        &#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;&#x2605;&nbsp;
                                    </span>
                                </p>
                                break;
                            }
                    }
                </div>
                <div>
                    <h2>@review.Title</h2>
                    <hr id="reviewHR"/>
                    <p>"@review.Message"</p>
                    <hr id="reviewHRDate"/>
                    <span id="reviewDate">@review.ReviewDate</span>
                </div>
                <div class="label label-primary pull-right priceLabels">
                    @review.Author
                </div>
            </div>
        }
        <footer class="col-md-12">
            <hr />
            @if (ViewData["empLoggedIn"].ToString() == "False")
                        {
                <p class="pull-left">&copy; 2017 - Pooch-Patrol</p>
                <form action="EmpLogin" method="get">
                    <a asp-controller="Employee" asp-action="EmpLogin" class="pull-right">Employee Login</a>
                </form>
            }
            else
            {
                <p class="pull-left">&copy; 2017 - Pooch-Patrol</p>
                <form method="post" asp-controller="Employee" asp-action="EmpLogout">
                    <button type="submit" class="btn btn-primary pull-right">Employee Log Out</button>
                </form>
            }
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

</body>
</html>

K9CleanSweep/Views/Shared/_Layout.cshtml
@model Client
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@{
    ViewData["clientID"] = K9CleanSweep.Startup.status.GetUserID();
    ViewData["loggedIn"] = K9CleanSweep.Startup.status.GetStatus();
    ViewData["empLoggedIn"] = K9CleanSweep.Startup.empStatus.GetStatus();
    ViewData["clientUserName"] = K9CleanSweep.Startup.status.GetUsername();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pooch-Patrol</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" id="userNavbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" id="brandName" asp-controller="Home" asp-action="Index">Pooch-Patrol</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Services">Rates</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Reviews">Reviews</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @if (ViewData["loggedIn"].ToString() == "True")
                { }
                else
                {
                    <a id="bookButton" asp-area="" class="pull-right" asp-controller="Home" asp-action="BookService">Sign Up</a>
                }
            </div>
        </div>
    </nav>
        @if (ViewData["loggedIn"].ToString() == "True")
        {
            <div id="login" class="col-md-12">
                <label class="label-info navbar-left" id="userBadge">Welcome&nbsp;@ViewData["clientUserName"]</label>
                <div class="text-center col-md-6">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Client" asp-action="LeaveReview">Leave FeedBack</a></li>
                        <li><a asp-area="" asp-controller="Client" asp-action="ClientOrder">Your Details</a></li>
                        <li><a asp-area="" asp-controller="Client" asp-action="Calendar">Service Date</a></li>
                    </ul>
                </div>
                <form class="navbar-form navbar-right" method="post" asp-action="Logout">
                    <button type="submit" class="btn btn-primary">Log Out</button>
                </form>
            </div>
        }
        else
        {
            <div id="login" class="col-md-12">
                <form class="navbar-form navbar-right" method="post" asp-action="Login" asp-controller="Client">
                    <div class="form-group">
                        <input asp-for="ClientUserName" type="text" class="form-control" placeholder="Username">
                        <input asp-for="Password" type="password" class="form-control" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                
            </div>
        }
    <div class="container body-content">
        @RenderBody()
    </div>
    <div class="col-md-12" id="canvasContainer">
        <canvas id="backgroundCanvas">
            Please update your browser to support Canvas
        </canvas>
        <canvas id="middleCanvas">
            Please update your browser to support Canvas
        </canvas>
        <canvas id="topCanvas">
            Please update your browser to support Canvas
        </canvas>
        <canvas id="veryTopCanvas">
            Please update your browser to support Canvas
        </canvas>
        <div id="weatherInfo">
            <img id="weatherIcon" src="" alt="WeatherIcon"/>
            <p id="weatherDesc"></p>
            <p id="weatherTemp"></p>
            <p id="weatherCityCountry"></p>
        </div>
    </div>
    @if (ViewData["empLoggedIn"].ToString() == "False")
    {
        <div id="footerContainer" class="col-md-12">
            <p class="pull-left">&copy; 2017 - Pooch-Patrol</p>
            <form action="EmpLogin" method="get">
                <a asp-controller="Employee" asp-action="EmpLogin" class="pull-right">Employee Login</a>
            </form>
        </div>
    }
    else
    {
        <p class="pull-left">&copy; 2017 - Pooch-Patrol</p>
        <form method="post" asp-controller="Employee" asp-action="EmpLogout">
            <button type="submit" class="btn btn-primary pull-right">Employee Log Out</button>
        </form>
    }
    <environment names="Development">
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCD9r9FBJGXpfr4MHUAjMu2H5mmiG6Rfqc&callback=initMap"
                async defer>
        </script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/practice.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>